#!/bin/sh
set -e
DKMS_NAME=vocalfusion-soundcard
DKMS_VERSION=0.0.2
case "$1" in
  remove|upgrade|deconfigure)
    if [ "$(dkms status -m $DKMS_NAME -v $DKMS_VERSION)" ]; then
      dkms remove -m $DKMS_NAME -v $DKMS_VERSION --all || true
    fi
  ;;
esac
exit 0
